# Cross-code reference test for the kinetics/equilibrium coupling.
#
# Calcite dissolves at a *constant* rate, so the kinetic half of Leal's system is
# analytic and every difference of rate-law convention between the two codes
# drops out. What is left is the question that matters: does the equilibrium
# partition follow nₑ(t) = φ(bₑ(t))?
#
# The oracle is generated by test/reference/reaktoro_coupling.py. Measured worst
# relative deviation over the trajectory: 0.3 % at t = 0, rising to 4.3 % at
# 3600 s, and always on CO₂@ — which sits at 2.3e-8 mol.

const RKC = Dict(
    0.0 => Dict("H2O@" => 55.4999999, "H+" => 9.99932289e-8, "OH-" => 9.99932289e-8, "CO2@" => 1.0e-16, "HCO3-" => 1.0e-16, "CO3-2" => 1.0e-16, "Ca+2" => 1.0e-16, "CaOH+" => 1.0e-16, "Ca(CO3)@" => 1.0e-16, "Ca(HCO3)+" => 1.0e-16),
    600.0 => Dict("H2O@" => 55.4997817, "H+" => 4.61324731e-11, "OH-" => 2.16731092e-4, "CO2@" => 2.25185714e-8, "HCO3-" => 2.17047539e-4, "CO3-2" => 2.20539072e-4, "Ca+2" => 4.36040374e-4, "CaOH+" => 1.56875542e-6, "Ca(CO3)@" => 1.61183646e-4, "Ca(HCO3)+" => 1.20722502e-6),
    1800.0 => Dict("H2O@" => 55.4996464, "H+" => 2.87008797e-11, "OH-" => 3.48350495e-4, "CO2@" => 2.25609913e-8, "HCO3-" => 3.49517142e-4, "CO3-2" => 5.7083373e-4, "Ca+2" => 9.1508186e-4, "CaOH+" => 5.29157253e-6, "Ca(CO3)@" => 8.75546793e-4, "Ca(HCO3)+" => 4.07977437e-6),
    3600.0 => Dict("H2O@" => 55.4995418, "H+" => 2.2318587e-11, "OH-" => 4.4794503e-4, "CO2@" => 2.26011019e-8, "HCO3-" => 4.50245132e-4, "CO3-2" => 9.45622653e-4, "Ca+2" => 1.38558729e-3, "CaOH+" => 1.03030974e-5, "Ca(CO3)@" => 2.19615184e-3, "Ca(HCO3)+" => 7.95777128e-6)
)
const K_RATE = 1.0e-6

@testset "Reaktoro reference: kinetics/equilibrium coupling" begin
    data = datapath("cemdata18-thermofun.json")
    dict = Dict(symbol(s) => s for s in build_species(data))
    aq = ["H2O@", "H+", "OH-", "CO2@", "HCO3-", "CO3-2", "Ca+2", "CaOH+", "Ca(CO3)@", "Ca(HCO3)+"]
    cs = ChemicalSystem([dict[s] for s in vcat(aq, "Cal")], ["H2O@", "H+", "Ca+2", "CO3-2", "Zz"])
    nm = symbol.(cs.species); idx(s) = findfirst(==(s), nm)
    spc = Dict(s => cs.species[idx(s)] for s in nm)
    rxn = Reaction(
        OrderedDict(spc["Cal"] => 1),
        OrderedDict(spc["Ca+2"] => 1, spc["CO3-2"] => 1);
        symbol = "Cal_diss", equal_sign = '→'
    )
    st = zeros(Float64, length(nm))
    st[idx("Cal")] = -1.0; st[idx("Ca+2")] = 1.0; st[idx("CO3-2")] = 1.0
    kr = KineticReaction(rxn, (T, P, t, n, lna, n0) -> K_RATE, idx("Cal"), st)

    n = Any[fill(0.0u"mol", length(nm))...]
    n[idx("H2O@")] = 55.5u"mol"; n[idx("Cal")] = 0.05u"mol"
    state = ChemicalState(cs, n)
    kp = KineticsProblem(
        cs, [kr], state, (0.0u"s", 3600.0u"s");
        equilibrium_solver = EquilibriumSolver(cs, DiluteSolutionModel(), OptimaOptimizer())
    )
    ks = KineticsSolver(;
        ode_solver = Rodas5P(), reltol = 1.0e-8, abstol = 1.0e-14,
        saveat = [0.0, 600.0, 1800.0, 3600.0]
    )
    sol = integrate(kp, ks)
    @test length(sol.t) == 4
    # The ODE state is (bₑ, nₖ); the equilibrium species are recovered by
    # φ(bₑ) — exactly what the oracle computes.
    sub = ChemistryLab._equilibrium_subsystem(cs, kp.idx_equilibrium)
    subnm = symbol.(sub.species)
    es = EquilibriumSolver(sub, DiluteSolutionModel(), OptimaOptimizer())
    n_be = size(kp.Ae, 1)
    for (ti, t) in enumerate(sol.t)
        haskey(RKC, t) || continue
        be = collect(sol.u[ti][1:n_be])
        guess = Any[fill(1.0e-10u"mol", length(subnm))...]
        guess[findfirst(==("H2O@"), subnm)] = 55.5u"mol"
        eq = ChemistryLab.SciMLBase.solve(es, ChemicalState(sub, guess); b = be)
        v = [ustrip(us"mol", x) for x in eq.n]
        ref = RKC[t]
        worst = 0.0; wsp = ""
        for (k, s) in enumerate(subnm)
            haskey(ref, s) || continue
            ref[s] > 1.0e-10 || continue
            r = abs(v[k] / ref[s] - 1)
            if r > worst
                worst = r; wsp = s
            end
        end
        @test worst < 0.05
    end
end
