# Cross-code reference test: calcite + CO₂ + water against Reaktoro 2.13.
#
# The oracle is generated by test/reference/reaktoro_calcite_co2.py, which reads
# the same Cemdata18 file, declares the same species, and uses ideal activities
# to match `DiluteSolutionModel()`. All three have to match: leaving Reaktoro on
# its HKF model instead shifts ∂Ca²⁺/∂(CO₂) by 35 %, which says nothing about
# either code.

# Reaktoro 2.13.0, Cemdata18, ideal activities
# finite-difference spread across h ∈ {1e-3, 1e-4, 1e-5}: 7.12e-4
const REAKTORO = Dict(
    "H2O@" => (n = 55.4961389, dn = -0.181397291),
    "H+" => (n = 3.69286738e-7, dn = 3.25691398e-5),
    "OH-" => (n = 2.70633096e-8, dn = -2.38767062e-6),
    "CO2@" => (n = 0.00613892838, dn = 0.818600249),
    "HCO3-" => (n = 0.00738915525, dn = 0.333426734),
    "CO3-2" => (n = 9.37864261e-7, dn = -4.03977783e-5),
    "Ca+2" => (n = 0.00352901991, dn = 0.151986657),
    "CaOH+" => (n = 1.58551676e-9, dn = -7.15930328e-8),
    "Ca(CO3)@" => (n = 5.54793457e-6, dn = -1.8134238e-8),
    "Ca(HCO3)+" => (n = 0.000332647348, dn = 0.029337739),
    "Cal" => (n = 0.0461327832, dn = -0.181324306),
)

# The oracle is itself a finite difference; nothing below its own step-size
# spread is meaningful, so that is the tolerance.
const RK_SPREAD = 7.12e-4

# ── TRACE_SPECIES_ARE_WRONG ───────────────────────────────────────────────────
#
# Species present below ~1e-5 mol do not agree with Reaktoro. Measured on this
# system, against Reaktoro reading the same database, the same species and the
# same activity model:
#
#     H+          1.24×      OH-        3.19×
#     CO3-2       1.10×      CaOH+     20.78×      Ca(CO3)@   1.02×
#
# so the water autoprotolysis comes out at pKw = 13.40 instead of 14.00. This
# matters: a cement pore solution lives at pH 13, and it is exactly these
# species that set it.
#
# The cause is conditioning, not thermodynamics. The element balance is
# satisfied to 4e-16 and the standard-state data is right — pure water gives
# pKw = 13.99. What fails is the *stationarity*: the interior-point iteration
# has to resolve amounts spanning ten orders of magnitude between the solvent
# at 55 mol and the trace ions at 1e-8, and the Hessian diagonal of an ideal
# Gibbs energy is 1/nᵢ, i.e. it spans the same ten orders. Both settings the
# back-end offers get half the problem right:
#
#   * `use_fd_hessian = true`  — finite-differences the diagonal, which is
#     correct for pure phases (constant activity, exact zero) but understates
#     the curvature on trace species, whose Newton step then overshoots;
#   * `use_fd_hessian = false` — uses 1/nᵢ everywhere, which is wrong for the
#     pure phases and sends the solve far off, wrong on major species too.
#
# Fixing this needs proper variable scaling in `OptimaSolver`, not a different
# Hessian formula. Until then these assertions are `@test_broken`, so a fix
# announces itself as an unexpected pass.
const TRACE_CUTOFF = 1.0e-5

const N_H2O, N_CAL, N_CO2 = 55.5, 0.05, 0.01

@testset "Reaktoro reference: calcite + CO₂ + water" begin
    data = joinpath(pkgdir(ChemistryLab), "data", "cemdata18-thermofun.json")
    dict = Dict(symbol(s) => s for s in build_species(data))
    syms = collect(keys(REAKTORO))
    cs = ChemicalSystem([dict[s] for s in syms], ["H2O@", "H+", "Ca+2", "CO3-2", "Zz"])
    names = symbol.(cs.species)

    ih2o = findfirst(==("H2O@"), names)
    ical = findfirst(==("Cal"), names)
    ico2 = findfirst(==("CO2@"), names)

    function speciate(x)
        n = Any[fill(0.0u"mol", length(cs.species))...]
        n[ih2o] = N_H2O * u"mol"
        n[ical] = N_CAL * u"mol"
        n[ico2] = x * u"mol"
        eq = equilibrate(ChemicalState(cs, n), OptimaOptimizer())
        return [ustrip(us"mol", v) for v in eq.n]
    end

    amounts = speciate(N_CO2)
    derivs = ForwardDiff.derivative(speciate, N_CO2)

    @testset "amounts agree with Reaktoro" begin
        # Species above ~1e-5 mol match Reaktoro to 1e-3 relative. Below that
        # they do not, and `@test_broken` records the defect rather than hiding
        # it: see the `TRACE_SPECIES_ARE_WRONG` note at the bottom of this file.
        for (k, name) in enumerate(names)
            ref = REAKTORO[name].n
            if ref > TRACE_CUTOFF
                @test amounts[k] ≈ ref rtol = 1.0e-3
            else
                @test_broken amounts[k] ≈ ref rtol = 1.0e-3
            end
        end
    end

    @testset "sensitivities agree with Reaktoro" begin
        # Species carrying a resolvable share of the response are compared
        # relatively; the rest only have to stay within the oracle's own noise.
        scale = maximum(abs(v.dn) for v in values(REAKTORO))
        for (k, name) in enumerate(names)
            ref = REAKTORO[name].dn
            if abs(ref) > 1.0e-3 * scale
                @test derivs[k] ≈ ref rtol = 2 * RK_SPREAD
            else
                @test abs(derivs[k] - ref) < RK_SPREAD * scale
            end
        end
    end

    @testset "AD matches this package's own finite differences" begin
        # This failed until the extension started handing the analytic gradient
        # `∂G/∂nᵢ = μᵢ` to the back-end: differencing a solve steered by an
        # inexact gradient against itself gave 0.118. It now agrees.
        h = 1.0e-6
        fd = (speciate(N_CO2 + h) - speciate(N_CO2 - h)) / (2h)
        @test maximum(abs, derivs - fd) < 1.0e-3
    end

    @testset "water autoprotolysis" begin
        # The tightest constraint there is, and one no thermodynamic database
        # can get wrong: pure water is electrically neutral, so [H⁺] = [OH⁻]
        # exactly, whatever Kw happens to be. It is a pure statement about the
        # solve. This failed — 4.03 instead of 1 — while the back-end was
        # steering on an approximated Hessian diagonal.
        csw = ChemicalSystem([dict[s] for s in ["H2O@", "H+", "OH-"]],
                             ["H2O@", "H+", "Zz"])
        nw = symbol.(csw.species)
        n = Any[fill(0.0u"mol", length(nw))...]
        n[findfirst(==("H2O@"), nw)] = 55.5u"mol"
        eq = equilibrate(ChemicalState(csw, n), OptimaOptimizer())
        v = [ustrip(us"mol", x) for x in eq.n]
        h, oh = v[findfirst(==("H+"), nw)], v[findfirst(==("OH-"), nw)]
        @test h ≈ oh rtol = 1.0e-4
        @test 13.9 < -log10(h * oh) < 14.1

        # And it stays fixed for the right reason: forcing the Schur complement
        # back on reproduces the old wrong answer, [H⁺]/[OH⁻] ≈ 3.78. If this
        # ever stops failing, the defect was cured elsewhere and the nullspace
        # step is no longer what is carrying the result.
        eqs = equilibrate(ChemicalState(csw, n), OptimaOptimizer(; nullspace_step = false))
        vs = [ustrip(us"mol", x) for x in eqs.n]
        @test vs[findfirst(==("H+"), nw)] / vs[findfirst(==("OH-"), nw)] > 2
    end

    @testset "element balance closes exactly" begin
        # Calcium has no source or sink here, so the sensitivities of every
        # Ca-bearing species must cancel. A finite difference only manages this
        # approximately; the KKT route is exact.
        ca = Dict(
            "Ca+2" => 1, "Cal" => 1, "CaOH+" => 1,
            "Ca(CO3)@" => 1, "Ca(HCO3)+" => 1
        )
        budget = sum(derivs[k] * get(ca, name, 0) for (k, name) in enumerate(names))
        @test abs(budget) < 1.0e-12
    end
end
