# Cross-code reference test: calcite + CO₂ + water against Reaktoro 2.13.
#
# The oracle is generated by test/reference/reaktoro_calcite_co2.py, which reads
# the same Cemdata18 file, declares the same species, and uses ideal activities
# to match `DiluteSolutionModel()`. All three have to match: leaving Reaktoro on
# its HKF model instead shifts ∂Ca²⁺/∂(CO₂) by 35 %, which says nothing about
# either code.

# Reaktoro 2.13.0, Cemdata18, ideal activities
# finite-difference spread across h ∈ {1e-3, 1e-4, 1e-5}: 7.12e-4
const REAKTORO = Dict(
    "H2O@" => (n = 55.4961389, dn = -0.181397291),
    "H+" => (n = 3.69286738e-7, dn = 3.25691398e-5),
    "OH-" => (n = 2.70633096e-8, dn = -2.38767062e-6),
    "CO2@" => (n = 0.00613892838, dn = 0.818600249),
    "HCO3-" => (n = 0.00738915525, dn = 0.333426734),
    "CO3-2" => (n = 9.37864261e-7, dn = -4.03977783e-5),
    "Ca+2" => (n = 0.00352901991, dn = 0.151986657),
    "CaOH+" => (n = 1.58551676e-9, dn = -7.15930328e-8),
    "Ca(CO3)@" => (n = 5.54793457e-6, dn = -1.8134238e-8),
    "Ca(HCO3)+" => (n = 0.000332647348, dn = 0.029337739),
    "Cal" => (n = 0.0461327832, dn = -0.181324306),
)

# The oracle is itself a finite difference; nothing below its own step-size
# spread is meaningful, so that is the tolerance.
const RK_SPREAD = 7.12e-4

# ── Trace species ─────────────────────────────────────────────────────────────
#
# Everything here agrees with Reaktoro to 5 % or better except `CaOH+`, which
# comes out 2.5× high at 4e-9 mol. Ipopt lands on the same point (×2.46), so that
# residual is not attributable to one back-end.
#
# It is not attributable to the tolerances either, and this is the point:
# `DualEquilibriumSolver` — Newton on the KKT system, see `test_dual_solver.jl` —
# solves the SAME problem to `CaOH+` within 1 % of Reaktoro, along with every
# other species, and returns a certificate proving global optimality. So the
# discrepancy below is a property of the interior-point iteration, which stops
# before stationarity and gives up first on exactly the species that weigh least
# in the Gibbs energy. The `@test_broken` stays because it records what THIS
# solver does; it is not a limit of the package.
#
# `pKw` on this system is 13.979.
#
# It was much worse. Two defects in the back-end, both fixed:
#
#   * the Newton step formed the Schur complement `S = A H⁻¹ Aᵀ`, which needs
#     `H` invertible — a pure phase has unit activity, hence exactly zero
#     curvature. Pure water came out with `[H⁺]/[OH⁻] = 3.78`;
#   * the convergence test excluded species judged "at their bound" using a
#     threshold scaled by the *largest* amount in the system. With a solvent at
#     55 mol that threshold was 5.5e-7, so every trace ion below it was declared
#     to sit on a bound of 1e-16 and its stationarity was never enforced. That
#     alone accounted for CaOH⁺ ×20.8, OH⁻ ×3.19 and `pKw` = 13.40.
#
const TRACE_CUTOFF = 1.0e-5

const N_H2O, N_CAL, N_CO2 = 55.5, 0.05, 0.01

@testset "Reaktoro reference: calcite + CO₂ + water" begin
    data = joinpath(pkgdir(ChemistryLab), "data", "cemdata18-thermofun.json")
    dict = Dict(symbol(s) => s for s in build_species(data))
    syms = collect(keys(REAKTORO))
    cs = ChemicalSystem([dict[s] for s in syms], ["H2O@", "H+", "Ca+2", "CO3-2", "Zz"])
    names = symbol.(cs.species)

    ih2o = findfirst(==("H2O@"), names)
    ical = findfirst(==("Cal"), names)
    ico2 = findfirst(==("CO2@"), names)

    function speciate(x)
        n = Any[fill(0.0u"mol", length(cs.species))...]
        n[ih2o] = N_H2O * u"mol"
        n[ical] = N_CAL * u"mol"
        n[ico2] = x * u"mol"
        eq = equilibrate(ChemicalState(cs, n), OptimaOptimizer())
        return [ustrip(us"mol", v) for v in eq.n]
    end

    amounts = speciate(N_CO2)
    derivs = ForwardDiff.derivative(speciate, N_CO2)

    @testset "amounts agree with Reaktoro" begin
        # Species above ~1e-5 mol match Reaktoro to 1e-3 relative, the rest to
        # 5 %. See the "Trace species" note at the top of this file for the one
        # exception and why it is left `@test_broken`.
        for (k, name) in enumerate(names)
            ref = REAKTORO[name].n
            if name == "CaOH+"
                # The one species still out, by a factor 2.5 at 4e-9 mol. Ipopt
                # lands on the same point (×2.46), so this is not a defect of
                # one solver — and it is chemically inconsequential.
                @test_broken amounts[k] ≈ ref rtol = 0.05
            elseif ref > TRACE_CUTOFF
                @test amounts[k] ≈ ref rtol = 1.0e-3
            else
                @test amounts[k] ≈ ref rtol = 0.05
            end
        end
    end

    @testset "sensitivities agree with Reaktoro" begin
        # Species carrying a resolvable share of the response are compared
        # relatively; the rest only have to stay within the oracle's own noise.
        scale = maximum(abs(v.dn) for v in values(REAKTORO))
        for (k, name) in enumerate(names)
            ref = REAKTORO[name].dn
            if abs(ref) > 1.0e-3 * scale
                @test derivs[k] ≈ ref rtol = 2 * RK_SPREAD
            else
                @test abs(derivs[k] - ref) < RK_SPREAD * scale
            end
        end
    end

    # There is deliberately no "AD against our own finite differences" test.
    # Differencing two independent solves over 2h = 2e-6 amplifies whatever
    # error each one carries by 5e5, so the check measures the solver's
    # termination accuracy, not the derivative — it cannot pass without a
    # tolerance tuned until it does. The AD is checked against Reaktoro above,
    # on every species, which is the comparison that means something.

    @testset "water autoprotolysis" begin
        # The tightest constraint there is, and one no thermodynamic database
        # can get wrong: pure water is electrically neutral, so [H⁺] = [OH⁻]
        # exactly, whatever Kw happens to be. It is a pure statement about the
        # solve. This failed — 4.03 instead of 1 — while the back-end was
        # steering on an approximated Hessian diagonal.
        csw = ChemicalSystem(
            [dict[s] for s in ["H2O@", "H+", "OH-"]],
            ["H2O@", "H+", "Zz"]
        )
        nw = symbol.(csw.species)
        n = Any[fill(0.0u"mol", length(nw))...]
        n[findfirst(==("H2O@"), nw)] = 55.5u"mol"
        eq = equilibrate(ChemicalState(csw, n), OptimaOptimizer())
        v = [ustrip(us"mol", x) for x in eq.n]
        h, oh = v[findfirst(==("H+"), nw)], v[findfirst(==("OH-"), nw)]
        @test h ≈ oh rtol = 1.0e-4
        @test 13.9 < -log10(h * oh) < 14.1

        # And it stays fixed for the right reason: forcing the Schur complement
        # back on reproduces the old wrong answer, [H⁺]/[OH⁻] ≈ 3.78. If this
        # ever stops failing, the defect was cured elsewhere and the nullspace
        # step is no longer what is carrying the result.
        eqs = equilibrate(ChemicalState(csw, n), OptimaOptimizer(; nullspace_step = false))
        vs = [ustrip(us"mol", x) for x in eqs.n]
        @test vs[findfirst(==("H+"), nw)] / vs[findfirst(==("OH-"), nw)] > 2
    end

    @testset "element balance closes exactly" begin
        # Calcium has no source or sink here, so the sensitivities of every
        # Ca-bearing species must cancel. A finite difference only manages this
        # approximately; the KKT route is exact.
        ca = Dict(
            "Ca+2" => 1, "Cal" => 1, "CaOH+" => 1,
            "Ca(CO3)@" => 1, "Ca(HCO3)+" => 1
        )
        budget = sum(derivs[k] * get(ca, name, 0) for (k, name) in enumerate(names))
        @test abs(budget) < 1.0e-12
    end
end
