# Cross-code reference test: calcite + CO₂ + water against Reaktoro 2.13.
#
# The oracle is generated by test/reference/reaktoro_calcite_co2.py, which reads
# the same Cemdata18 file, declares the same species, and uses ideal activities
# to match `DiluteSolutionModel()`. All three have to match: leaving Reaktoro on
# its HKF model instead shifts ∂Ca²⁺/∂(CO₂) by 35 %, which says nothing about
# either code.

# Reaktoro 2.13.0, Cemdata18, ideal activities
# finite-difference spread across h ∈ {1e-3, 1e-4, 1e-5}: 7.12e-4
const REAKTORO = Dict(
    "H2O@" => (n = 55.4961389, dn = -0.181397291),
    "H+" => (n = 3.69286738e-07, dn = 3.25691398e-05),
    "OH-" => (n = 2.70633096e-08, dn = -2.38767062e-06),
    "CO2@" => (n = 0.00613892838, dn = 0.818600249),
    "HCO3-" => (n = 0.00738915525, dn = 0.333426734),
    "CO3-2" => (n = 9.37864261e-07, dn = -4.03977783e-05),
    "Ca+2" => (n = 0.00352901991, dn = 0.151986657),
    "CaOH+" => (n = 1.58551676e-09, dn = -7.15930328e-08),
    "Ca(CO3)@" => (n = 5.54793457e-06, dn = -1.8134238e-08),
    "Ca(HCO3)+" => (n = 0.000332647348, dn = 0.029337739),
    "Cal" => (n = 0.0461327832, dn = -0.181324306),
)

# The oracle is itself a finite difference; nothing below its own step-size
# spread is meaningful, so that is the tolerance.
const RK_SPREAD = 7.12e-4

const N_H2O, N_CAL, N_CO2 = 55.5, 0.05, 0.01

@testset "Reaktoro reference: calcite + CO₂ + water" begin
    data = joinpath(pkgdir(ChemistryLab), "data", "cemdata18-thermofun.json")
    dict = Dict(symbol(s) => s for s in build_species(data))
    syms = collect(keys(REAKTORO))
    cs = ChemicalSystem([dict[s] for s in syms], ["H2O@", "H+", "Ca+2", "CO3-2", "Zz"])
    names = symbol.(cs.species)

    ih2o = findfirst(==("H2O@"), names)
    ical = findfirst(==("Cal"), names)
    ico2 = findfirst(==("CO2@"), names)

    function speciate(x)
        n = Any[fill(0.0u"mol", length(cs.species))...]
        n[ih2o] = N_H2O * u"mol"
        n[ical] = N_CAL * u"mol"
        n[ico2] = x * u"mol"
        eq = equilibrate(ChemicalState(cs, n), OptimaOptimizer())
        return [ustrip(us"mol", v) for v in eq.n]
    end

    amounts = speciate(N_CO2)
    derivs = ForwardDiff.derivative(speciate, N_CO2)

    @testset "amounts agree with Reaktoro" begin
        for (k, name) in enumerate(names)
            ref = REAKTORO[name].n
            @test amounts[k] ≈ ref rtol = 1.0e-3
        end
    end

    @testset "sensitivities agree with Reaktoro" begin
        # Species carrying a resolvable share of the response are compared
        # relatively; the rest only have to stay within the oracle's own noise.
        scale = maximum(abs, values(map(v -> v.dn, REAKTORO)))
        for (k, name) in enumerate(names)
            ref = REAKTORO[name].dn
            if abs(ref) > 1.0e-3 * scale
                @test derivs[k] ≈ ref rtol = 2 * RK_SPREAD
            else
                @test abs(derivs[k] - ref) < RK_SPREAD * scale
            end
        end
    end

    @testset "AD matches this package's own finite differences" begin
        h = 1.0e-6
        fd = (speciate(N_CO2 + h) - speciate(N_CO2 - h)) / (2h)
        @test maximum(abs, derivs - fd) < 1.0e-3
    end

    @testset "element balance closes exactly" begin
        # Calcium has no source or sink here, so the sensitivities of every
        # Ca-bearing species must cancel. A finite difference only manages this
        # approximately; the KKT route is exact.
        ca = Dict("Ca+2" => 1, "Cal" => 1, "CaOH+" => 1,
                  "Ca(CO3)@" => 1, "Ca(HCO3)+" => 1)
        budget = sum(derivs[k] * get(ca, name, 0) for (k, name) in enumerate(names))
        @test abs(budget) < 1.0e-12
    end
end
