pages = [
    "Home" => "index.md",
    "Getting Started" => "quickstart.md",
    "Tutorial" => [
        "man/formula_manipulation.md",
        "man/species.md",
        "man/cement_species.md",
        "man/databases.md",
        "man/stoich_matrices.md",
        "man/reactions.md",
        "man/thermodynamics.md",
        "man/chemical_system_state.md",
        "man/equilibrium.md",
        "man/kinetics.md",
        "man/coupling.md",
        "man/reaktoro_comparison.md",
        "man/advanced.md",
    ],
    "Examples" => [
        "examples/bogue_calculation.md",
        "examples/example_stoich_matrix.md",
        "examples/from_scratch.md",
        "examples/titration_acetic_acid.md",
        "examples/titration_maleic_acid.md",
        "examples/co2_carbonate_system.md",
        "examples/simplified_clinker_dissolution.md",
        # "examples/cement_wc_ratio.md",
        "examples/cement_carbonation.md",
        "examples/cement_clinker_kinetics.md",
        "examples/coupled_hydration.md",
        "examples/ionic_hydration.md",
        "examples/hydration_calibration.md",
    ],
    "API" => Any[
        "Thermodynamical functions" => "api/thermo_functions.md",
        "Thermodynamical models" => "api/thermo_models.md",
        "Water properties" => "api/water_properties.md",
        "Element order" => "api/element_order.md",
        "Parsing tools" => "api/parsing_tools.md",
        "Formulas" => "api/formulas.md",
        "Species" => "api/species.md",
        "Stoichiometric Matrix" => "api/stoich_matrices.md",
        "Reactions" => "api/reactions.md",
        "Databases" => "api/databases.md",
        "Chemical systems and states" => "api/chemical_systems.md",
        "Equilibrium" => "api/equilibrium.md",
        "Kinetics" => "api/kinetics.md",
        "Utilities" => "api/utils.md",
    ],
    "References" => "references.md",
]
